var i = 0;
var products = [
    "LG 65-Inch 4K OLED TV",
    "Samsung 65-Inch QLED Smart TV",
    "Apple iPhone16 Pro Titanium",
    "Samsung Galaxy S23",
    "Oneplus 11 5G",
    "Whirlpool 240L Double-Door Refrigerator",
    "LG 190L Single-Door Refrigerator",
    "Samsung Washing Machine",
    "Whirlpool Washing Machine",
    "LG Dishwasher",
    "Haier Dishwasher",
    "Apple MacBook Air M2",
    "Dell Inspiron 15",
    "HP Pavilion x360",
    "Bose QuietComfort 45",
    "Apple AirPods Pro (2nd Gen)",
    "Sony WH-1000XM5 Noise Cancelling Headphones",
    "Samsung Galaxy Watch 6",
    "Apple Watch Series 9",
    "Xiaomi Mi Smart Band 6",
    "Canon EOS R50 Mirrorless Camera",
    "Sony ZV-E10 Mirrorless Camera",
    "GoPro HERO12 Action Camera",
    "Samsung Galaxy Tab S9",
    "Apple iPad Air (10.9-inch)",
    "Amazon Fire HD 10",
    "LG 2.1 Channel Soundbar",
    "Epson EcoTank L3250 All-in-One Printer",
    "HP LaserJet Pro MFP",
    "Canon PIXMA MG3070S",
    "Sony PlayStation 5",
    "Philips Steam Iron",
    "Preethi Zodiac Mixer Grinder",
    "Instant Vortex Plus Air Fryer",
    "Cuisinart 14-Cup Food Processor",
    "KitchenAid Stand Mixer",
    "The Alchemist",
    "Man's Search for Meaning",
    "The Night Circus",
    "It Ends with Us",
    "The Silent Patient",
    "Gone Girl",
    "A Game of Thrones",
    "The Hobbit",
    "Atomic Habits",
    "The Power of Now",
    "Meditations",
    "The Republic",
    "Steve Jobs",
    "Becoming",
    "The Gruffalo",
    "Harry Potter and the Sorcerer's Stone",
    "Sapiens: A Brief History of Humankind",
    "Tefal Non-Stick Fry Pan",
    "Prestige Induction Cooker",
    "Philips Induction Stove",
    "Milton Airtight Storage Containers (Set of 10)",
    "Amazon Bamboo Drawer Organizer",
    "IKEA Spice Rack",
    "Philips 600W Hand Blender",
    "Bajaj 3-in-1 Electric Griller",
    "Cello 1.7L Electric Kettle",
    "Philips Air Fryer",
    "Bosch Food Processor",
    "Black+Decker Coffee Maker",
    "Amazon Wooden Storage Cabinet",
    "Seville Classics 3-Tier Rolling Cart",
    "Urban Ladder Office Chair",
    "Amazon Microfiber Bed Sheet Set (King Size)",
    "Wakefit Memory Foam Pillow",
    "Wipro LED Ceiling Light",
    "Philips Hue Table Lamp",
    "Long Cylindrical Candles",
    "Designer Cup Candles",
    "Godrej Decorative Wall Mirror",
    "Godrej Decorative Wall Mirror",
    "Cotton Casual Shirt",
    "Slim Fit Denim Jeans",
    "Round Neck Graphic T-Shirt",
    "A-Line Maxi Dress",
    "High-Waist Skinny Jeans",
    "Chiffon Floral Scarf",
    "Boys' Cotton Polo T-Shirt",
    "Girls' Party Wear",
    "Unisex Hooded Sweatshirt",
    "Running Shoes",
    "Leather Formal Shoes",
    "Casual Loafers",
    "Ballet Flats",
    "Heeled Sandals",
    "Sneakers",
    "Chronograph Watch",
    "Digutal Watch",
    "Rose Gold Analog Watch",
    "Bracelet Watch",
    "Leather Wallet",
    "Aviator Sunglasses",
    "Tote Bag",
    "Designer Clutch",
    "Kurta Set",
    "Cotton Nehru Jacket",
    "Embroidered Anarkali Suit",
    "Printed Saree with Blouse",
    "Leather Backpack",
    "Waterproof Hiking Backpack",
    "Travel & Trekking Backpack",
    "Maybelline Liquid Foundation",
    "Lakme Compact Powder",
    "Sugar Contour & Highlighter Palette",
    "Loreal Waterproof Eyeliner",
    "Maybelline Volumizing Mascara",
    "Huda Eyeshadow Palette (All Shades)",
    "MAC Matte Lipstick",
    "Nykaa Liquid Lipstick",
    "Nivea Lip Balm",
    "Luxury Perfume (100ml)",
    "Colorbar Nail Polish Set (Glossy Finish)",
    "OPI Gel Nail Polish Remover",
    "Garnier BB Cream",
    "Smashbox Primer",
    "Loreal Hair Serum",
    "Schwarzkopf Styling Hair Spray",
    "Gatsby Strong Hold Hair Gel",
    "Ustraa Matte Finish Hair Clay",
    "OGX Curl Defining Mousse",
    "Livon Anti-Frizz Hair Cream",
    "Tresemme Heat Protection Spray",
    "Dr.Trust Digital Thermometer",
    "Omron BP Monitor",
    "Beurer Pulse Oximeter",
    "GNC Multivitamin Gummies",
    "Muscle Blaze Protein Powder",
    "Amazon Yoga Mat",
    "Kore Dumbbell Set",
    "Organic India Herbal Tea",
    "Dettol Hand Sanitizer",
    "3M Face Mask (Pack of 10)",
    "Savlon Disinfectant Spray",
    "Caresmith Electric Massager",
    "Dr.Physio Heating Pad",
    "Morpheus Sleep Mask",
    "Hot Wheels Track Builder",
    "Barbie Dreamhouse Doll Set",
    "NERF Elite Blaster",
    "Hasbro Monopoly Classic Board Game",
    "Mattel UNO Card Game",
    "Rastar Remote Control Car",
    "Hamley's Teddy Bear",
    "Funskool Junior Doctor Kit",
    "Rubik's Cube 3x3",
    "Funskool Chess Set",
    "Casio Musical Keyboard for Kids",
    "Yonex Badminton Racket Set",
    "MRF Cricket Bat",
    "Adidas Football",
    "Wilson Tennis Racket",
    "Nike Basketball",
    "Callaway Golf Club Set",
    "Strauss Skipping Rope",
    "Healthgenie Exercise Cycle",
    "Stag Table Tennis Set",
    "Super Carrom Board",
    "Hasbro Ludo Board Game",
    "Funskool Snake and Ladder Game",
    "Nivia Badminton Net",
    "Cosco Volleyball Net",
    "Toyshine Bowling Set",
    "Johnson's Baby Soap",
    "Johnson's Baby Shampoo",
    "Pampers Baby Diapers (Pack of 40)",
    "Huggies Baby Wipes (Pack of 72)",
    "Pigeon Baby Lotion",
    "Chicco Baby Carrier",
    "LuvLap Baby Walker",
    "Philips Baby Feeding Bottle",
    "Babyhug Baby Clothes Set (5 Pcs)",
    "Mothercare Baby Socks (Pack of 5)",
    "Pigeon Baby Nail Clippers",
    "Curaprox Baby Toothbrush",
    "Graco Baby Car Seat",
    "Wheat Flour (5kg)",
    "Sugar (1kg)",
    "Salt (1kg)",
    "Cooking Oil (L)",
    "Ghee (500g)",
    "Soya Sauce (250ml)",
    "Tomato Ketchup (500g)",
    "Chilli Powder (100g)",
    "Turmeric Powder (100g)",
    "Cumin Powder (100g)",
    "Cardomom (50g)",
    "Ginger-Garlic Paste (200g)",
    "Tamarind Paste (200g)",
    "Toor Dal (1kg)",
    "Moong Dal (1kg)",
    "Chana Dal (1kg)",
    "Dried Raisins (250g)",
    "Cashews (200g)",
    "Almonds (200g)",
    "Pistachios (200g)",
    "Oats (1kg)",
    "Cornflakes (500g)",
    "Toor Dal (1kg)",
    "Honey (500g)",
    "Peanut Butter (200g)",
    "Jam (200g)",
    "Chili Sauce (250g)",
    "Mayonnaise (300g)",
    "Green Peas (400g)",
    "Coriander Powder (100g)",
    "Chili Flakes (100g)",
    "Black Pepper (100g)",
    "Cumin Seeds (100g)",
    "Mustard Seeds (100g)",
    "Kashmiri Red Chili Powder (100g)",
    "Basmati Rice (1kg)",
    "Tea Bags (100 count)",
    "Instant Coffee (100g)",
    "Whole Wheat Pasta (500g)",
    "2-min Instant Noodles",
    "Baking Sode (200g)",
    "Pedigree Dog Food",
    "Whiskas Cat Food",
    "Himalaya Pet Shampoo",
    "Trixie Dog Collar",
    "Dog Leash",
    "Petmate Pet Bed",
    "Prevue Hendryx Bird Cage",
    "Aqua One Fish Tank",
    "Midwest Rabbit Cage",
    "Vision Parrot Cage",
    "Formula 1 Car Dashboard Cleaner",
    "Meguiar's Car Wax",
    "Black+Decker Tyre Inflator",
    "Autozone Car Seat Covers",
    "Ambi Pur Car Air Freshener",
    "Black+Decker Car Vacuum Cleaner",
    "Ecoshine Car Sunshade",
    "Koolertron Car Seat Organizer",
    "Castrol Car Engine Oil",
    "Parker Fountain Pen",
    "Faber-Castell School Kit",
    "B2B A4 paper (500 Sheets)",
    "Classmate Notebook (200 Pages)",
    "Post-it Sticky Notes (Pack of 5)",
    "Rorito Whiteboard Marker Set (4 Colors)",
    "Kangaroo Stapler",
    "Nataraj Paper Clips (Pack of 100)",
    "Faber-Castell Scissors (8 Inches)",
    "Q-Connect File Folders (Pack of 10)",
    "HP Printer Ink (Black)",
    "Casio Calculator",
    "Rubbermaid Whiteboard (3x4 Feet)",
    "Fellowes Folders with Clip (Pack of 5)",
    "Scotch Push Pins (Pack of 50)",
    "Camlin Envelope (Pack of 100)",
    "Stanley Paper Cutter",
    "Stanley Hammer (16oz)",
    "Dewalt Screwdriver Set (6 Pcs)",
    "Komelon Measuring Tape",
    "Bosch Electric Drill Machine",
    "Stanley Utility Knife",
    "Knipex Plier Set (4 Pcs)",
    "Stanley Toolbox (Large)",
    "Krause Ladder (6 Feet)",
    "Tanishq Diamond Necklace",
    "Cartier Gold Earrings",
    "Bvlgari Platinum Ring",
    "Van Cleef Emerald Bracelet",
    "Mikimoto Pearl Necklace",
    "Rolex Gold Watch",
    "Diamond Stud Earrings",
    "Chopard Sapphire Ring",
    "Pandora Silver Anklet",
    "Tanishq Pearl Necklace Set",
    "CaratLane Gold-Plated Drop Earrings",
    "Nest Smart Thermostat",
    "Philips Smart Light Bulb",
    "August Smart Door Lock",
    "Ring Smart Security Camera",
    "Amazon Echo Smart Speaker",
    "iRobot Automatic Vacuum Cleaner",
    "Haier Robot Floor Cleaner",
    "Ring Smart Doorbell",
    "Nest Smart Smoke Detector",
    "Lutron Smart Curtain",
    "Dyson Smart Air Purifier",
    "Samsonite Luggage Set",
    "Cabeau Travel Pillow",
    "Bose Noise Cancelling Headphones",
    "Anker Portable Charger",
    "Zendure Travel Adapter",
    "Bellroy Travel Wallet",
    "Osprey Foldable Backpack",
    "Cocoon Compact Travel Blanket",
    "Hydro Flask Portable Water Bottle",
    "Nomatic Travel Backpack",
    "Bose Blu-ray Player",
    "Sony Home Theater System",
    "DVD Player",
    "JBL Soundbar",
    "Epson Projector EB-E01",
    "Samsung 4K Blu-ray Player",
    "Vizio 5.1 Channel Soundbar",
    "BenQ 1080p Projector",
    "Sony PlayStation 5 Console",
    "Microsoft Zbox Wireless Controller",
    "Minecraft for PS4",
    "Razer Gaming Headset",
    "Logitech Gaming Mouse"
];

var image_url=[];
var parser=new DOMParser();

async function getImage() {
    for(let i=0;i<products.length;i++){
        var product=products[i].split(" ").join("+");
        var url=`https://www.amazon.in/s?k=${product}&ref=nb_sb_noss`;
        
        var response=await fetch(url);
        var data=await response.text();
        var parse=parser.parseFromString(data, "text/html");

        var src=parse.querySelector(".s-image").src;
        image_url.push(src);
        console.log("URL : ",src);

        await new Promise(resolve => setTimeout(resolve,500));
    }
    downloadFile();
}

function downloadFile(){
    let urlContent=image_url.join("\n");
    let blob=new Blob([urlContent], {type: "text/plain"});

    let link=document.createElement("a");
    link.href=URL.createObjectURL(blob);
    link.download="image_urls.txt";
    document.body.append(link);
}

getImage();